# Generated by Django 2.2.16 on 2023-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230508_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(null=True, related_name='posts', to='posts.Group', verbose_name='группа'),
        ),
    ]
